version: '3.8'

services:
  url-shortener:
    image: shortener:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    environment:
      - PORT=8080
      - ANALYTICS_URL=http://analytics:8081
    networks:
      - app-network

  analytics:
    image: analytics:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      - PORT=8081
    networks:
      - app-network

  nginx:
    image: nginx-fixed:latest
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - app-network

networks:
  app-network:
    driver: overlay