version: '3.8'

services:
  url-shortener:
    image: shortener:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
    environment:
      - PORT=8080
      - ANALYTICS_URL=http://analytics:8081
    networks:
      - swarm-network
    # ВРЕМЕННО УБИРАЕМ HEALTHCHECK для отладки
    # healthcheck:
    #   test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  analytics:
    image: analytics:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
    environment:
      - PORT=8081
    networks:
      - swarm-network
    # ВРЕМЕННО УБИРАЕМ HEALTHCHECK
    # healthcheck:
    #   test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  nginx:
    image: nginx-fixed:latest
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
    networks:
      - swarm-network
    depends_on:
      - url-shortener
      - analytics

networks:
  swarm-network:
    driver: overlay